language: node_js
node_js:
  - "6"
install:
  - npm install
script:
  - gulp build
  - fractal build
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "encrypted_6a4d0aaec6ec_key"
  - COMMIT_AUTHOR_EMAIL: "digital@boston.gov"
