language: node_js
node_js:
- '6'
before_install:
- rvm install 2.4.0
install:
- yarn install
- gem install percy-cli
script:
- gulp build
- fractal build
after_script:
- percy snapshot public --baseurl "/components" --snapshots_regex="(?!components/detail)"
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  deploy.sh
env:
  global:
  - secure: DQrWraUARyNuUA1KXDT1IJxQG6SrflD622+TX1SKeL0UemhxzliGMBqOgYt2KSrXqTjzimUcGyeSpJhC3hM5ACgNF3ft3Eikw5/2jc9P8oBRzPafnm/QtbD2EI5rwA+VxjqmSbP6rh49CB/ftnkymp0OLH0PD3Epw7BwlmoPPRueyh3uAR5YyMcfSuVaEeJMu6sk3hKaPF0ykGxqDKJcNs0dw50V2hBqYoaj9aWvsvLYZO7j/vrz8Qm+/m7bm0TDVXsnjwTpuSvpSPPQZW4ul92DldYSrvEXxBOL0tSjYa3+uEjto7WZlkRHUgtDvoznxQImrYCpSwlSh1VJdG+JB9STj5xD/+6LPrQiW4s9Q3BPP4KPneT71wTDaaPVE3syx/ZlhK0qBOqhd+KqFdzQ5+r4vysOc8MKVRGtBHJ/7dbN+27wguV9KE/10c2Ln+FUs7TVBnWKhwarT5erVj36/zdWNEPFtZSj41uYwKUc1Q2gwPnyzf6wA49P8UDgIISqWDEWRA6fuDpPZbwP4KGdlLjyAD/CT6ZgyEoLZpmSVRRJ4P/MraSRCaN28dsR/6YrddgpHcZfcngGF79ftP3EsP0Y34lU/UEgQuB+gfz5b5UxeF3VY8uApEl1q8llz/6SKZsrUZ3VVPbb3gMoylgsWmAlfC2v9KcdLC05Ry6YO14=
  matrix:
  - secure: bzmaXAQi/lUsAfdyQMhBMFbafNN7j3TlRA+mTzjqmyfPmsMwb6gYn1zzpv3jBrt03zv7rXKoQShmDHrXD1YKLcUC/R/lsKp31R4yCLV4TJC3TT8YyF2KMJrmbnpX4uH9erOBgNIkMl00C9NnMiCUnfgY3wUNS2rWy2muzz4QtKuzCmm+gHAY4t2jelkQKtCcX/26O927Sac/jXLaL2Qr6ig4e2GHdKA+vNbwXi6zQqUhXJZSJWTH1XED3gIyByAsPLYL+Toh3Oav9L3sIA6ybq4k1m3sEnrCDt8sYY0l4VQwmkpsVixvF39F56sgeaO+/3fO/beVUgJgq6xF2MRS6zv5+Dg2efZYPS2A957Tk9i9DZel8f1c4wbSd1fR2lUGig7MlxGUrJPLIAh32Oa1qntbzFCfTczjv/JFEuqPUKJz7ZKdSeYqwB8nRKa58WtFHIBrrsFvcdaZTaCc/ZbHbGw1iQwMNkJvse6TlJCneDoMX9ptLOiVgTBzhHnF3ImfR0VGj/irIsUfC7mcar3HUOMl5AiYivcx56cKg2aifx2l1EdNIwQ5odo22AvBfBdP36KfFoAk2MNZWrI1JI6s5/Io2JZi3bnrIE1jAQZCLHZJopZXqM49Vm6l26+xCL9OHxkiW06gAWImpkO7oAT7Jy4S/Iundmp6fH7nO28rbfg=
  - secure: bRh4sR2Nv50xwpgZCBSSY92GwpAzgE3pWWKsuMLm4Wz1eixzfDMnCmuUsv9BkRfZ3Fxt7Z0T5nrz3pM0FIpatgjmYqY1Vs7A2VWKkjDip/yGUfVQcgNsHooJ6NWEQ2Dd1U5AGo3RgLJDuIWfsKCvfr3/QYbgTiHCSwzm+7IFEkN+IokOPBe5hka+cjNTIEZ1xnF2V8OGv98k3aadz6sOjl7rREBH+nDFxPsHRoksmouVRK+a/myYQb/FKJiFDISg3ow+NMDc/+JdP9pKWWpV2IZcMnStGfH11NwXUFC0V6Lur8QxhORaHeSXnUQdt79/dFtsa/GOxERDnTXEBzhXX1hPMxmMecMrviyVTmPyFjmpX1MknAAim5T25hBYHxkvEezjLPYLXqwpnrGlzsEtEMxnFhmqMl4BAM7VrViDgzbXPjfdlbK3GuaRvyYNEVr0cXCzkYHzyS6TB31w7mMR1HiHTF+nuKFMOhYEHKh2H4jKNwHklg7dwS6LHoQCEFLkQJOFIxoMj7LgNs99sknLW66TOChXUy7QMtTHZUB6HYtd3TGjN752u0HcO5nQutg/h6/JQfSwA1HUdaNunM3YjTi9ygjw2Z3fZoRzspJFRMXhNGqGu49BrzvcKyAJ+IItOde/2pFei9VuWbk/jYFV7hjgnNxm5JXZWXZ4mLX2oUU=
notifications:
  slack:
    rooms:
      secure: IgW7hkOkPSiECu21oCWelA97WTYzVroPdvByLrmRB6gMlLZLK8MKqIoztXXyC6igyrNSV9HWlU4V6xsCpT/RGj4ybj6Z6lU5BEFTe4c1gC1aNEvaKsaTLu2W78RkgigMDJQlQMR4eIoyS8lUeXEwL2GH+l8foSMAa92y2nYHNE/0PSwebru1UsiVaO8zVGqWUbcakee8yFhB2Bt+NpU8MaU7PS8dYb/gzUv9b7XsA2ZMWqytlI8rHWuedX3GKRQugRatLcHtUPYE8mAa6g2mxyupdLIrj1PfLDx1//ySSzengZqT8rHxyYRM7zOT5/UDmCsHd09RXhw47xCNvDX5ES7dmXICDZfsUlNvjzTVXzeGZWUlbTxEupYtUQMCpPLLCBCZy6iLFNHWiqFJ8UizhQ/7tWAyWGP4LEBJj1jR354l5BuRPXHHNIRQP6uhZkk6RvWI0DWEPQR2qaH/aBHVOH65ZQIGqRPNu5uy2r5qWQpm8uRaXGO7DtN+MP9G3RVU9n6WA84LAjNRtAgYgrDJ2d0A6XxKqOfI8gs0YDZuPyDVuh4zO+ZBSl6nDCEqyKTHWNkplM7tHgQX7fdjdZ2PKCt0VsnzO9xeAfRRB7DZoLBkwUP2KQooWmlrt0OCKXtKA4TSDBG+eO4MdUsUaF1zwWORbLJsOv7e/78h2s5iiyg=
