title: Common Transactions
handle: grid_transactions
status: ready
variants:
  - name: hub
    status: 'ready'
    preview: '@hub'
context:
  header:
    title: Starting Transactions
    contact: false
  links:
    - name: Pay a parking ticket for Boston
      href: https://www.boston.gov/departments/parking-clerk/how-pay-parking-ticket
      image: https://cdn.rawgit.com/CityOfBoston/bostonicons/master/experiential/pay_taxes.svg
    - name: Pay a parking ticket
      href: https://www.boston.gov/departments/parking-clerk/how-pay-parking-ticket
      image: https://cdn.rawgit.com/CityOfBoston/bostonicons/master/experiential/pay_taxes.svg
    - name: Pay a parking ticket
      href: https://www.boston.gov/departments/parking-clerk/how-pay-parking-ticket
      image: https://cdn.rawgit.com/CityOfBoston/bostonicons/master/experiential/pay_taxes.svg
    - name: Pay a parking ticket
      href: https://www.boston.gov/departments/parking-clerk/how-pay-parking-ticket
      image: https://cdn.rawgit.com/CityOfBoston/bostonicons/master/experiential/pay_taxes.svg
    - name: Pay a parking ticket for Boston
      href: https://www.boston.gov/departments/parking-clerk/how-pay-parking-ticket
      image: https://cdn.rawgit.com/CityOfBoston/bostonicons/master/experiential/pay_taxes.svg
    - name: Pay a parking ticket
      href: https://www.boston.gov/departments/parking-clerk/how-pay-parking-ticket
      image: https://cdn.rawgit.com/CityOfBoston/bostonicons/master/experiential/pay_taxes.svg
    - name: Pay a parking ticket
      href: https://www.boston.gov/departments/parking-clerk/how-pay-parking-ticket
      image: https://cdn.rawgit.com/CityOfBoston/bostonicons/master/experiential/pay_taxes.svg
    - name: Pay a parking ticket
      href: https://www.boston.gov/departments/parking-clerk/how-pay-parking-ticket
      image: https://cdn.rawgit.com/CityOfBoston/bostonicons/master/experiential/pay_taxes.svg
