title: Social Media
handle: social-media
status: ready
context:
  icons:
    - file: icon-facebook.svg
    - file: icon-flickr.svg
    - file: icon-instagram.svg
    - file: icon-linkedin.svg
    - file: icon-tumblr.svg
    - file: icon-twitter.svg
    - file: icon-youtube.svg
