title: Mapping
handle: mapping
status: ready
context:
  icons:
    - file: bathroom.svg
    - file: bathroom-light-bg.svg
    - file: food-basket.svg
    - file: food-truck.svg
    - file: parking.svg
    - file: parking-nope.svg
    - file: outdoor-pool.svg
    - file: tot-spray.svg
    - file: trash-recycling.svg
    - file: waypoint-charles-blue.svg
    - file: waypoint-freedom-red.svg
    - file: waypoint-optimistic-blue.svg
    - file: closed-roads.svg
