title: Drawer
handle: drawer
status: ready
variants:
  - name: Hub
    preview: '@hub'
context:
  drawers:
    - index: 1
      title: 'November 8, 2016: General Election'
      subtitle: 'Last updated: 2/2017'
      content: '<p>Here is some test content.</p><p>Here is some test content.</p><p>Here is some test content.</p><p>Here is some test content.</p>'
