title: 'Web Components: Map'
handle: map
status: ready
context:
  heading: Parking and city councilors
variants:
  - name: Address Search
    context:
      show_address_search: true
      open_overlay: true

  - name: Cluster Icons
    context:
      cluster_icons: true

  - name: Overlay Open
    context:
      open_overlay: true
