title: 'Text Box'
handle: textbox
status: ready
context:
  inputType: true
  textareaType: false
  textboxes:
    - label: First name
      placeholder: First name
      value: Carol Danvers
    - label: Email
      placeholder: Your email address
      value: ""
variants:
  - name: Textarea
    context:
      inputType: false
      textareaType: true
