title: 'Text Box'
handle: textbox
status: ready
context:
  inputType: true
  textareaType: false
  textboxes:
    - label: First name
      placeholder: First name
      value: Carol Danvers
      id: text
    - label: Email
      placeholder: Your email address
      value: ""
      id: text
variants:
  - name: Textarea
    context:
      id: text
      inputType: false
      textareaType: true
  - name: Error
    context:
      inputType: true
      textareaType: false
      textboxes:
        - label: First name
          placeholder: First name
          value: Carol Danvers
          id: text
        - label: Email
          placeholder: Your email address
          value: ""
          id: text
          error: Please enter an email address
