title: 'Tabs'
handle: tabs
status: wip
context:
  links:
    - text: New applicants
      link: '#new_applicants'
    - text: Renew your certificate
      link: '#renew_certificate'
      selected: true
    - text: Change your address
      link: '#change_address'
    - text: Withdraw your business
      link: '#withdraw_business'
