title: Hero
handle: hero
status: wip
variants:
  - name: With Call to Action
    status: 'wip'
    context:
      home: true
      intro: welcome to the new
      title: Boston.gov
      subheader: Mayor Martin J. Walsh
      cta:
        text: View Mayor's profile
        link: https://boston.gov/mayor
      image:
        wide1x: https://www.boston.gov/sites/default/files/styles/rep_wide_2000x700custom_boston_wide_1x/public/hero-image-07-2016/25832647073_167d235f54_o.jpg?itok=nWpQdSFD&amp;timestamp=1469541909
        desktop1x: https://www.boston.gov/sites/default/files/styles/rep_wide_2000x700custom_boston_desktop_1x/public/hero-image-07-2016/25832647073_167d235f54_o.jpg?itok=GJmuhNoE&amp;timestamp=1469541909
        tablet1x: https://www.boston.gov/sites/default/files/styles/rep_wide_2000x700custom_boston_tablet_1x/public/hero-image-07-2016/25832647073_167d235f54_o.jpg?itok=g19HCDkD&amp;timestamp=1469541909
        mobile1x: https://www.boston.gov/sites/default/files/styles/rep_wide_2000x700custom_boston_mobile_1x/public/hero-image-07-2016/25832647073_167d235f54_o.jpg?itok=XzPWArjL&amp;timestamp=1469541909
  - name: Without Subheader
    status: 'wip'
    context:
      home: true
      intro: welcome to the new
      title: Boston.gov
      cta: false
      image:
        wide1x: https://www.boston.gov/sites/default/files/styles/rep_wide_2000x700custom_boston_wide_1x/public/hero-image-07-2016/25832647073_167d235f54_o.jpg?itok=nWpQdSFD&amp;timestamp=1469541909
        desktop1x: https://www.boston.gov/sites/default/files/styles/rep_wide_2000x700custom_boston_desktop_1x/public/hero-image-07-2016/25832647073_167d235f54_o.jpg?itok=GJmuhNoE&amp;timestamp=1469541909
        tablet1x: https://www.boston.gov/sites/default/files/styles/rep_wide_2000x700custom_boston_tablet_1x/public/hero-image-07-2016/25832647073_167d235f54_o.jpg?itok=g19HCDkD&amp;timestamp=1469541909
        mobile1x: https://www.boston.gov/sites/default/files/styles/rep_wide_2000x700custom_boston_mobile_1x/public/hero-image-07-2016/25832647073_167d235f54_o.jpg?itok=XzPWArjL&amp;timestamp=1469541909
  - name: No Image
    status: 'wip'
    context:
      intro: false
      title: How to apply for a business certificate
      subheader: Companies in Boston need to get a business certificate through the City Clerk’s office. You need to renew your certificate every four years.
      image: false
      cta: false
context:
  home: true
  intro: Welcome to the new
  title: Boston.gov
  subheader: Mayor Martin J. Walsh
  cta: false
  image:
    wide1x: https://www.boston.gov/sites/default/files/styles/rep_wide_2000x700custom_boston_wide_1x/public/hero-image-07-2016/25832647073_167d235f54_o.jpg?itok=nWpQdSFD&amp;timestamp=1469541909
    desktop1x: https://www.boston.gov/sites/default/files/styles/rep_wide_2000x700custom_boston_desktop_1x/public/hero-image-07-2016/25832647073_167d235f54_o.jpg?itok=GJmuhNoE&amp;timestamp=1469541909
    tablet1x: https://www.boston.gov/sites/default/files/styles/rep_wide_2000x700custom_boston_tablet_1x/public/hero-image-07-2016/25832647073_167d235f54_o.jpg?itok=g19HCDkD&amp;timestamp=1469541909
    mobile1x: https://www.boston.gov/sites/default/files/styles/rep_wide_2000x700custom_boston_mobile_1x/public/hero-image-07-2016/25832647073_167d235f54_o.jpg?itok=XzPWArjL&amp;timestamp=1469541909
