title: Department Icon
handle: department_icon
status: wip
context:
  department:
    name: Innovation and Technology
    icon: https://www.boston.gov/sites/default/files/department_icons/icons_doit.svg
    url: /departments/innovation-and-technology
