title: 'Form: Search'
handle: form_search
status: ready
variants:
  - name: Small
    context:
      theme: sm
      show_label: false
  - name: Yellow
    context:
      theme: y

context:
  show_label: true
  term: City Clerk
