title: 'Button'
handle: button
status: ready
variants:
  - name: 'Yellow'
    context:
      theme: 'y'
  - name: 'Charles Blue'
    context:
      theme: 'c'
context:
  buttons:
    - label: Next
      type: button
    - label: Next
      disabled: true
      type: button
    - label: Next
      type: a
    - label: Next
      type: a
      class: 'btn--sm btn--100'
