title: 'Checkbox'
handle: checkbox
status: ready
context:
  checkboxes:
    - label: Public Notices
      index: 0
    - label: Intergovernmental Relations
      index: 1
    - label: Here is a really long label that will wrap at some point.
      index: 2
